-- One-time seed from the final registry.json (16 entries).
-- Apply with:
--   wrangler d1 execute demo-registry --remote --file=seed.sql
--
-- `deleted_at` is pre-set on the entries that index.html used to suppress via
-- its HIDDEN_IDS array, so the soft-delete column now carries that state.

insert into demos
  (id, title, type, url, summary, tags, screenshots, added_by, added, edited, deleted_at)
values
  ('2026-06-19-agentic-loan-workflow-pitch', 'Agentic loan workflow pitch', 'demo', 'https://example.com/replace-me', 'Front + back office loan demo showing an agentic redesign of the loan approval workflow. Includes a clickable prototype and a presentation deck.', '["lending", "agentic", "nordpension", "front-and-back-office"]', '[]', 'jeprasher@gmail.com', '2026-06-19', null, null),
  ('2026-07-03-home-loan-agent', 'Home-loan agent', 'video', 'https://implementcg.sharepoint.com/sites/2023-0526/_layouts/15/stream.aspx?id=%2Fsites%2F2023%2D0526%2FDelte%20dokumenter%2FGeneral%2F0%2E3%20Templates%20and%20guides%2Fdemos%2Fboligl%C3%A5n%2Emov&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E23a5bb16%2D163f%2D4c60%2Dbcfd%2D46610a440db0', 'Receives the application, collects documents, performs the credit assessment and presents a finished recommendation for one-click adviser approval', '["agent-system", "lending", "home-loan", "danish"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-17f78c0b.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-03', null),
  ('2026-07-03-credit-assessment-agent', 'Credit-assessment agent', 'video', 'https://implementcg.sharepoint.com/sites/2023-0526/_layouts/15/stream.aspx?id=%2Fsites%2F2023%2D0526%2FDelte%20dokumenter%2FGeneral%2F0%2E3%20Templates%20and%20guides%2Fdemos%2Fkundem%C3%B8de%2Dforberedelse%2Emov&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ebac1692a%2Dc661%2D456f%2D95dd%2D68e946aeb73c', 'The agent automatically pulls data from internal systems and external bureaus, assesses changes in the customer''s finances and flags cases that require human attention.', '["agent-system", "credit", "nordea", "english"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-71f651cf.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-08bdb7aa.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-c34c44f7.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-9580325c.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-03', null),
  ('2026-07-03-estate-administration-agent', 'Estate-administration agent', 'video', 'https://drive.google.com/file/d/1Da_n_3WjfKYqWXZuGLfMLaeva9u1eu5H/view', 'The agent maps the deceased''s finances, identifies assets and debt, generates a draft statement and coordinates communication with heirs and authorities.', '["agent-system", "estate", "sydbank", "danish"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-424562a3.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-2a40ddfc.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-6b564153.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-0df20bfe.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-03', null),
  ('2026-07-03-ai-risk-management-tool', 'AI risk-management tool', 'demo', 'https://nordea-risk-tool.lovable.app/', 'AI-assisted risk management that lets you identify, structure and ask questions about your organisation''s risks via a chat interface.', '["ai-workflow", "risk", "nordea", "english"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-a9ebf5bf.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-b04be987.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-3ab40865.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-df2018a6.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-03', null),
  ('2026-07-03-kyc-odd-edd-aml-kyc-co-pilot', 'KYC / ODD / EDD - AML KYC Co-pilot', 'demo', 'https://6a16fb9c1af2050008dacfc3--kyc-odd-edd.netlify.app/', 'AI agent orchestration of KYC onboarding and the ongoing updating of ODD and EDD.', '["agent-system", "kyc", "aml", "compliance", "danish"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-d3983393.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-cee274d9.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-29dd183b.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-56776af6.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-03', null),
  ('2026-07-03-aml-alert-handling-compliance-workbench', 'AML alert handling - Compliance Workbench', 'demo', 'https://alarm-behandler.fly.dev/', 'AI-supported handling of AML alerts: gathers and prioritises alerts, assesses risk signals and helps quickly triage the cases that require follow-up, incl. suggested handling options.', '["compliance", "aml", "workbench", "english"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-ab3fe290.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-6317b191.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-96932f1e.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-dd20726b.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-03', null),
  ('2026-07-03-project-method', 'Project method', 'demo', 'https://ca-benefit-react.victoriousocean-e7e97192.swedencentral.azurecontainerapps.io/deliverables', 'Agent-builder demo showing a project-method deliverables view. Author: Michel Poesze.', '["agent-builder", "project-method", "english"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-a69c11ca.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-10', null),
  ('2026-07-03-crewing-agent', 'Crewing agent', 'demo', 'https://ca-crewing-react.lemonglacier-39e18a8e.swedencentral.azurecontainerapps.io/', 'Agent-builder crewing demo. Login protected - password: IM-agentic-crewing-26. Author: Michel Poesze.', '["agent-builder", "crewing", "english"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-3e89bffa.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-dd447883.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-10', null),
  ('2026-07-03-fuji-deviation-management', 'Fuji deviation management', 'demo', 'https://ca-counter-fda-frontend.redmeadow-d53948d0.swedencentral.azurecontainerapps.io/', 'Deviation-management demo (Fuji). Author: Bertalan.', '["deviation-management", "quality", "english"]', '[]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-03', null),
  ('2026-07-03-ai-report-builder', 'AI report builder', 'video', 'https://drive.google.com/file/d/1jG3ffJdzS9lR3q58rB19WdtrgGxLBMIU/view?usp=drive_link', 'Creates professional reports in minutes from uploaded data; exports to PDF, PPTX or DOCX.', '["document-creator", "reporting", "english"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-4513ea31.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-075789eb.png"]', 'jere@thetechcollective.eu', '2026-07-03', '2026-07-10', null),
  ('2026-07-03-complaint-document-agent-klageskrift', 'Complaint document agent (Klageskrift)', 'video', 'https://drive.google.com/file/d/1jNMcCfmSJPc27n67Mqe0fyLYhl9vaWPN/view?usp=drive_link', 'Agent that drafts a complaint document (klageskrift). Author: Magnus Berg Sletfjerding.', '["agent-system", "legal", "klageskrift", "danish"]', '[]', 'jere@thetechcollective.eu', '2026-07-03', null, null),
  ('2026-07-03-order-to-invoice-agentic-demo', 'Order-to-Invoice Agentic Demo', 'demo', 'https://claude.ai/artifacts/latest/fb033450-7874-48d6-8859-ac1142dfc55d', 'Ten AI Agents running order entry, order processing, invoicing and stock replenishment instead of traditional Customer Service.

A PO arrives by email in PDF format. Agents take it from there: one extracts the data from the PDF, converts units against the ERP automatically, checks for third-party material, tracks delivery and installation status, and drafts and sends the invoice. Two agents run independently of any single order, one watches the inbox, one monitors stock levels and automatically creates replenishment orders. The associate steps in only to approve the order and the invoice.', '["order-to-invoice", "customer-care", "sap", "salesforce", "customer-service", "order-processing"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-03-da703e7b.png"]', 'Anastasia Frøsig', '2026-07-03', '2026-07-29', '2026-08-25'),
  ('2026-07-10-car-loan-front-back', 'Car loan - front & back', 'demo', 'https://claude.ai/artifacts/latest/7ab62eb6-fa25-42e3-99f1-ea36b34782f0', 'A ''front & back'' walkthrough of an agentic car-loan application. Left: what the customer and advisor see - a chat plus one mini-app per bank system (Case, Documents, Credit, Advisory, Core). Right: behind the scenes - a 9-stage process ribbon and a top-to-bottom agent graph handling the case. Steps through a DKK 400,000 Audi Q4 e-tron loan over 72 months, with a human approval gate in the Advisory system (you can ask the agent a question in chat before approving).', '["car-loan", "banking", "agentic", "front-and-back", "credit", "advisory", "human-in-the-loop"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-57ff5940.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-90cb0897.png", "https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-dd755f4a.png"]', 'jere@thetechcollective.eu', '2026-07-10', '2026-07-10', null),
  ('2026-07-10-s-oe-meeting-prep', 'S&OE meeting prep', 'demo', 'https://claude.ai/artifacts/latest/737d1da5-01d8-4d9c-8838-90acedb3fdde', 'Front + back office demo of the S&OE prep agent (Agent 1 of the cycle) for Lundbeck. Wakes on the meeting invite at T-2 days, pulls APS, CRM and the action tracker, drafts the pre-read, and hands it to the planner to approve and distribute. The allocation conflict is flagged for the meeting to decide, never proposed by the agent.', '["s&oe", "supply-chain", "agentic", "lundbeck", "pharma", "front-and-back-office", "prep-agent"]', '["https://raw.githubusercontent.com/jepras/demo-registry/main/screenshots/2026-07-10-3be045bd.png"]', 'jere@thetechcollective.eu', '2026-07-10', null, null),
  ('2026-08-14-order-to-invoice-agentic-demo', 'Order-to-Invoice Agentic Demo', 'demo', 'https://claude.ai/artifacts/latest/fb033450-7874-48d6-8859-ac1142dfc55d', 'Back-office order entry and invoicing (PO intake to dispatch) redesigned with 10 agents; two human approval gates retained (order approval, invoice approval).', '["agentic-ai", "order-to-cash", "customer-care", "sap", "salesforce"]', '[]', 'Anastasia', '2026-08-14', null, null);
